##
##  Makefile -- Build procedure for sample rootme Apache module
##  Autogenerated via ``apxs -n rootme -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib
LDFLAGS+=-lutil

SRCS = mod_rootme.c mrm_server.c

mod_rootme.so: $(SRCS)

# the default target
all: mod_rootme.so
	$(APXS) $(INCLUDES) -c $(SRCS) $(LDFLAGS) $(LIBS) 

$(builddir)/.deps:
	$(MKDEP) $(EXTRA_CPPFLAGS) $(EXTRA_INCLUDES) $(SRCS) > $@

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_rootme.o mod_rootme.lo mod_rootme.slo mod_rootme.la .deps

#   simple test
test: reload
	lynx -mime_header http://localhost/rootme

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

